// Generated by scripts/demo-drawings.mjs. Do not edit: change the script and run it again.
// The sample projects' drawings: where each marked area and issue pin goes (fractions of the sheet).
export interface DemoDrawingSpec {
  key: string; file: string; title: string; sheet: string; discipline: 'architectural' | 'structural' | 'services' | 'site' | 'other';
  width: number; height: number;
  zones: { name: string; stage: string; x: number; y: number; w: number; h: number }[];
  pins: { issue: number; x: number; y: number }[];
}
export const DEMO_DRAWINGS: DemoDrawingSpec[] = [
  {
    key: 'adenta',
    file: 'adenta-a101',
    title: 'Ground floor plan',
    sheet: 'A-101',
    discipline: 'architectural',
    width: 1680,
    height: 1188,
    zones: [
      {
        name: 'West wing',
        stage: 'Blockwork',
        x: 0.1488,
        y: 0.1684,
        w: 0.1381,
        h: 0.537
      },
      {
        name: 'Living and dining',
        stage: 'Lintel level',
        x: 0.2869,
        y: 0.1684,
        w: 0.1726,
        h: 0.537
      },
      {
        name: 'Hall and stairs',
        stage: 'Lintel level',
        x: 0.4595,
        y: 0.1684,
        w: 0.1208,
        h: 0.3418
      },
      {
        name: 'East wing',
        stage: 'Lintel level',
        x: 0.5804,
        y: 0.1684,
        w: 0.1208,
        h: 0.3418
      },
      {
        name: 'Kitchen and store',
        stage: 'First floor slab',
        x: 0.4595,
        y: 0.5101,
        w: 0.2417,
        h: 0.1953
      }
    ],
    pins: [
      {
        issue: 0,
        x: 0.6857,
        y: 0.2806
      }
    ]
  },
  {
    key: 'legon',
    file: 'legon-s201',
    title: 'First floor slab, general arrangement',
    sheet: 'S-201',
    discipline: 'structural',
    width: 1680,
    height: 1188,
    zones: [
      {
        name: 'Bays A to C',
        stage: 'First floor slab',
        x: 0.125,
        y: 0.2104,
        w: 0.2411,
        h: 0.4091
      },
      {
        name: 'Bays C to E',
        stage: 'First floor slab',
        x: 0.3661,
        y: 0.2104,
        w: 0.2411,
        h: 0.4091
      },
      {
        name: 'Bays E to F',
        stage: 'Roof level',
        x: 0.6071,
        y: 0.2104,
        w: 0.1205,
        h: 0.4091
      },
      {
        name: 'Stair and lift core',
        stage: 'Lintel level',
        x: 0.7277,
        y: 0.3468,
        w: 0.1205,
        h: 0.1364
      }
    ],
    pins: [
      {
        issue: 1,
        x: 0.7582,
        y: 0.4059
      }
    ]
  },
  {
    key: 'road',
    file: 'road-c301',
    title: 'Drainage layout, CH 2+000 to 2+600',
    sheet: 'C-301',
    discipline: 'site',
    width: 1680,
    height: 1188,
    zones: [
      {
        name: 'Left drain 2+000 to 2+300',
        stage: 'Drains and culverts',
        x: 0.0833,
        y: 0.303,
        w: 0.4167,
        h: 0.032
      },
      {
        name: 'Right drain 2+300 to 2+600',
        stage: 'Drains and culverts',
        x: 0.5,
        y: 0.5404,
        w: 0.4167,
        h: 0.032
      },
      {
        name: 'Culvert C3',
        stage: 'Drains and culverts',
        x: 0.2708,
        y: 0.2694,
        w: 0.0417,
        h: 0.3367
      },
      {
        name: 'Base course',
        stage: 'Base course',
        x: 0.0833,
        y: 0.3788,
        w: 0.8333,
        h: 0.1178
      },
      {
        name: 'Shoulders',
        stage: 'Surfacing',
        x: 0.0833,
        y: 0.4966,
        w: 0.8333,
        h: 0.0219
      }
    ],
    pins: [
      {
        issue: 0,
        x: 0.6528,
        y: 0.319
      }
    ]
  }
];
